Add FAQ item for too old pyopenssl version issue
Add FAQ item to describe the reason and solution for issue "AttributeError: 'X509' object has no attribute '_x509'"